# dbt Project Configuration for MyLife Analytics
name: 'mylife_analytics'
version: '1.0.0'
config-version: 2

# Project profile (defined in profiles.yml)
profile: 'mylife_analytics'

# Source and target directories
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  mylife_analytics:
    # Materialization defaults
    +materialized: view

    # Bronze layer - raw data from sources
    bronze:
      +materialized: view
      +schema: bronze
      spotify:
        +tags: ["spotify", "bronze", "source"]
      maps:
        +tags: ["maps", "bronze", "source"]

    # Silver layer - cleaned, deduplicated data
    silver:
      +materialized: view
      +schema: silver
      spotify:
        +tags: ["spotify", "silver", "cleaned"]
      maps:
        +tags: ["maps", "silver", "cleaned"]

    # Gold layer - aggregated, dashboard-ready data
    gold:
      +materialized: table
      +schema: gold
      # Refresh gold tables on each run
      +on_schema_change: "sync_all_columns"
      spotify:
        +tags: ["spotify", "gold", "dashboard"]
      maps:
        +tags: ["maps", "gold", "dashboard"]

# Tests
tests:
  +store_failures: true
  +schema: dbt_test_failures

# Documentation
vars:
  # Date range for analysis (last N days)
  lookback_days: 365
