spotify_analytics:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: clickhouse
      schema: "{{ env_var('CLICKHOUSE_DATABASE', 'bronze') }}"
      host: "{{ env_var('CLICKHOUSE_HOST_DEV', 'localhost') }}"
      port: "{{ env_var('CLICKHOUSE_PORT_DEV', '8123') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'admin') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', 'clickhouse08062013') }}"
      secure: false
      verify: false
    prod:
      type: clickhouse
      schema: "{{ env_var('CLICKHOUSE_DATABASE', 'bronze') }}"
      host: "{{ env_var('CLICKHOUSE_HOST_PROD', 'clickhouse') }}"
      port: "{{ env_var('CLICKHOUSE_PORT_PROD', '9000') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'admin') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      secure: false
      verify: false