spotify_analytics:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: localhost
      port: 8123
      user: admin
      password: clickhouse08062013
    prod:
      type: clickhouse
      host: clickhouse
      port: 9000
      user: admin
      password: clickhouse08062013