version: 2

models:
  - name: silver_spotify_tracks
    description: >
      Cleaned and deduplicated Spotify listening history. Removes duplicates and adds derived time dimensions.
    columns:
      - name: track_id
        description: Unique identifier for the track
        tests:
          - not_null
      - name: track_name
        description: Name of the track
        tests:
          - not_null
      - name: artist_id
        description: Primary artist ID
        tests:
          - not_null
      - name: played_at
        description: Timestamp when track was played
        tests:
          - not_null
          - unique
      - name: track_duration_ms
        description: Track duration in milliseconds
      - name: track_duration_minutes
        description: Track duration in minutes (derived)
      - name: played_date
        description: Date when track was played (derived)
      - name: played_hour
        description: Hour of day when track was played (0-23)
      - name: day_of_week
        description: Day of week (1=Monday, 7=Sunday)

  - name: silver_spotify_artists
    description: >-
      Latest details for each artist from the Spotify API. Automatically updates when new artist data is ingested.
    columns:
      - name: artist_id
        description: Unique identifier for the artist
        tests:
          - not_null
          - unique
        data_type: string
      - name: artist_name
        description: Name of the artist
        tests:
          - not_null
        data_type: string
      - name: popularity
        description: Artist popularity score (0-100)
        data_type: uint64
      - name: followers_total
        description: Total number of followers on Spotify
        data_type: uint64
      - name: genres
        description: Array of genres associated with the artist
        data_type: array(string)
      - name: last_updated
        description: When this artist data was last fetched
        data_type: datetime64(3)
      - name: artist_uri
        data_type: string
        quote: true
      - name: artist_type
        data_type: string
        quote: true
      - name: image_url
        data_type: string
        quote: true
      - name: images_urls
        data_type: array(string)
        quote: true
      - name: images_heights
        data_type: array(uint64)
        quote: true
      - name: images_widths
        data_type: array(uint64)
        quote: true
      - name: external_url_spotify
        data_type: string
        quote: true
      - name: source
        data_type: string
        quote: true

  - name: silver_google_maps_activities
    description: >
      Cleaned and enriched Google Maps activity data with temporal attributes
      and location details. Removes duplicates and adds derived dimensions for analysis.
    columns:
      - name: activity_id
        description: Unique identifier generated from activity details
        data_type: uint64
        tests:
          - not_null
          - unique
      - name: activity_time
        description: Timestamp when the activity occurred
        data_type: datetime64(3)
        tests:
          - not_null
      - name: activity_date
        description: Date of the activity
        data_type: date
      - name: activity_hour
        description: Hour of day (0-23)
        data_type: uint8
      - name: day_of_week
        description: Day of week (1=Monday, 7=Sunday)
        data_type: uint8
      - name: day_name
        description: Name of the day (e.g., 'Monday')
        data_type: string
      - name: week_start
        description: Start date of the week
        data_type: date
      - name: month_start
        description: Start date of the month
        data_type: date
      - name: year
        description: Year of the activity
        data_type: uint16
      - name: month
        description: Month number (1-12)
        data_type: uint8
      - name: quarter
        description: Quarter number (1-4)
        data_type: uint8
      - name: time_of_day
        description: Time period classification (Morning/Afternoon/Evening/Night)
        data_type: string
      - name: is_weekend
        description: Flag indicating if activity occurred on weekend (1=yes, 0=no)
        data_type: uint8
      - name: location_name
        description: Name of the location
        data_type: string
        tests:
          - not_null
      - name: location_url
        description: Google Maps URL for the location
        data_type: string
      - name: location_address
        description: Address of the location
        data_type: string
      - name: latitude
        description: Latitude coordinate
        data_type: float64
      - name: longitude
        description: Longitude coordinate
        data_type: float64
      - name: has_coordinates
        description: Flag indicating if coordinates are available (1=yes, 0=no)
        data_type: uint8
      - name: products_list
        description: Comma-separated list of Google products used
        data_type: string
