mappings:
  # Airflow DAG metrics
  - match: "airflow.dagrun.*.*.duration"
    name: "airflow_dagrun_duration"
    labels:
      dag_id: "$1"
      status: "$2"

  - match: "airflow.dagrun.*.*.count"
    name: "airflow_dagrun_count"
    labels:
      dag_id: "$1"
      status: "$2"

  # Airflow Task metrics
  - match: "airflow.task.*.*.*.duration"
    name: "airflow_task_duration"
    labels:
      dag_id: "$1"
      task_id: "$2"
      status: "$3"

  - match: "airflow.task.*.*.*.count"
    name: "airflow_task_count"
    labels:
      dag_id: "$1"
      task_id: "$2"
      status: "$3"

  # Airflow Scheduler metrics
  - match: "airflow.scheduler.*.count"
    name: "airflow_scheduler_count"
    labels:
      metric: "$1"

  - match: "airflow.scheduler.heartbeat"
    name: "airflow_scheduler_heartbeat"

  # Airflow Executor metrics
  - match: "airflow.executor.*.count"
    name: "airflow_executor_count"
    labels:
      metric: "$1"

  - match: "airflow.executor.open_slots"
    name: "airflow_executor_open_slots"

  - match: "airflow.executor.queued_tasks"
    name: "airflow_executor_queued_tasks"

  - match: "airflow.executor.running_tasks"
    name: "airflow_executor_running_tasks"

  # Airflow Pool metrics
  - match: "airflow.pool.*.slots"
    name: "airflow_pool_slots"
    labels:
      pool: "$1"
      type: "open"

  - match: "airflow.pool.*.running_slots"
    name: "airflow_pool_slots"
    labels:
      pool: "$1"
      type: "running"

  - match: "airflow.pool.*.queued_slots"
    name: "airflow_pool_slots"
    labels:
      pool: "$1"
      type: "queued"

  # Task Instance metrics
  - match: "airflow.ti.*.*.*.count"
    name: "airflow_ti_count"
    labels:
      dag_id: "$1"
      task_id: "$2"
      state: "$3"

  - match: "airflow.ti_failures"
    name: "airflow_ti_failures_total"

  - match: "airflow.ti_successes"
    name: "airflow_ti_successes_total"

  # DAG Processing metrics
  - match: "airflow.dag_processing.last_duration.*"
    name: "airflow_dag_processing_last_duration"
    labels:
      dag_file: "$1"

  - match: "airflow.dag_processing.last_run.seconds_ago.*"
    name: "airflow_dag_processing_last_run_seconds_ago"
    labels:
      dag_file: "$1"

  # Catch-all for other airflow metrics
  - match: "airflow.*"
    name: "airflow_${1}"
    labels: {}